# Generated by Django 3.1.1 on 2020-09-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200905_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_for', to='app.company'),
        ),
    ]
